services:
  - type: web
    name: neurostack
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: https://neurostack.onrender.com
      - key: SEED_DB
        value: "true"
      - key: PYTHON_VERSION
        value: "3.11.9"
